spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ataraxia
spring.datasource.username=postgres
spring.datasource.password=YHV1135353*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080